const CATEGORIES = [
    {
        title: 'Telefony',
        link: '/telefony',
        subCategories: [{ title: 'Chytré telefony', link: '/chytre_telefony' }, 
                        { title: 'Tlačítkový telefon', link: '/tlacitkove_telefony' }, 
                        // { title: 'Ostatní', link: '/ostatni' },
                    ],
    },
    {
        title: 'Počítače',
        link: '/pocitace',
        subCategories: [{ title: 'Notebooky', link: '/notebooky' }, 
                        { title: 'Personalní Počítače', link: '/personalni_pocitace' },
                        { title: 'Herní Počítače', link: '/herni_pocitace' },
                        // { title: 'Ostatní', link: '/ostatni' },
                    ],
    },
    {
        title: 'Velke spotrebice',
        link: '/velke_spotrebice',
        subCategories: [{ title: 'Ledničky', link: '/lednicky' }, 
                        { title: 'Pračky', link: '/pracky' },
                        { title: 'Klimatizace', link: '/klimatizace' },
                        // { title: 'Ostatní', link: '/ostatni' },
                    ],
    },
    {
        title: 'Projektory',
        link: '/projektory',
    },
    // {
    //     title: 'Nářadí a nástroje',
    //     link: '/naradi_a_nastroje',
    //     subCategories: [{ title: 'Laboratorní a měřící technika',link: '/laboratorni_a_merici_technika' }, 
    //                     { title: 'Chemie',link: '/chemie' }, 
    //                     { title: 'Elektrické nářadí',link: '/electricke_naradi' }, 
    //                     { title: 'Ruční nářadí',link: '/rucni_naradi' },],
    // },
    // {
    //     title: 'Audio, Video, Výpočetní technika',
    //     link: '/clothes',
    //     subCategories: [{ title: 'Anténní technika' ,link: '/antenni_technika'}, 
    //         { title: 'Audio, Video',link: '/audio_video' }, 
    //         { title: 'Výpočetní technika',link: '/vypocetni_technika' }, 
    //         { title: 'Kancelářské a prezentační pomůcky',link: '/Kancelarske_a_prezentacni_pomucky' }, 
    //         { title: 'Propojovací kabely',link: '/propojovaci_kabely' }, 
    //         { title: 'Elektronické převodníky a přepínače',link: '/elektronicke_prevodniky_a_prepinace' }],
    // },
    // {
    //     title: 'Zdroje energie',
    //     link: '/zdroje_energie',
    //     subCategories: [{ title: 'Baterie' ,link: '/baterie'}, 
    //                     { title: 'Akumulátory a nabíjecí baterie',link: '/akumulatory_a_nabijeci_baterie' }, 
    //                     { title: 'Bateriová pouzdra a držáky',link: '/bateriova_pouzdra_a_drzaky' }, 
    //                     { title: 'Powerbanky',link: '/powerbanky' }, 
    //                     { title: 'Alternativní zdroje energie',link: '/alternativni_zdroje_energie' }, 
    //                     { title: 'Napájecí zdroje AC/DC',link: '/napajeci_zdroje_ac_dc' }, 
    //                     { title: 'Nabíječky baterií',link: '/nabijecky_baterii' }],
    // },
]

export default CATEGORIES;